## This workflow is structured slightly differently than usual.
## There are three manifests:
## - a set of experimental vcfs, with unique aliases
## - a set of reference sample vcfs, with unique aliases
## - a set of comparisons between experimental and reference vcfs, referred to by their aliases from the other two manifests
## This structure is a little complicated, but is designed to keep the configuration as streamlined as possible.
## Unfortunately, these kinds of comparisons are inherently a little messy.

experiment-manifest: "config/manifest_experiment.tsv"
## the GIAB links were extracted from the Octopus publication, supplemental note 1, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7611855/#SD1
reference-manifest: "config/manifest_reference.tsv"
comparisons-manifest: "config/manifest_comparisons.tsv"



genome-build: "grch37"



genomes:
  grch37:
    fasta: "s3://invitae-health-chameleon-dev/reference_data/grch37/human_g1k_v37_modified/human_g1k_v37_modified.fasta"
