## This workflow is structured slightly differently than usual.
## There are three manifests:
## - a set of experimental vcfs, with unique aliases
## - a set of reference sample vcfs, with unique aliases
## - a set of comparisons between experimental and reference vcfs, referred to by their aliases from the other two manifests
## This structure is a little complicated, but is designed to keep the configuration as streamlined as possible.
## Unfortunately, these kinds of comparisons are inherently a little messy.

experiment-manifest: "config/manifest_experiment.tsv"
## the GIAB links were extracted from the Octopus publication, supplemental note 1, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7611855/#SD1
reference-manifest: "config/manifest_reference.tsv"
comparisons-manifest: "config/manifest_comparisons.tsv"
happy-bedfiles-per-stratification: 3
genome-build: "grch37"

## Stratification regions are suggested for use with hap.py style analysis. All thanks to Justin Zook lol
genomes:
  grch37:
    fasta: "s3://invitae-health-chameleon-dev/reference_data/grch37/human_g1k_v37_modified/human_g1k_v37_modified.fasta"
    confident-regions:
      AY52:
        bed: "/locus/data/assays/AY52/targets/v1/annotated_targets.bed"
      AY85:
        bed: "/locus/data/assays/AY85/targets/v1/annotated_targets.bed"
      all:
        bed: "resources/grch37.bed"
      NA12878_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/NA12878_HG001/latest/GRCh37/HG001_GRCh37_1_22_v4.2.1_benchmark.bed"
        inclusion: "NA12878"
      NA24385_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh37/HG002_GRCh37_1_22_v4.2.1_benchmark_noinconsistent.bed"
        inclusion: "NA24385"
      NA24149_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG003_NA24149_father/latest/GRCh37/HG003_GRCh37_1_22_v4.2.1_benchmark_noinconsistent.bed"
        inclusion: "NA24149"
      NA24143_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG004_NA24143_mother/latest/GRCh37/HG004_GRCh37_1_22_v4.2.1_benchmark_noinconsistent.bed"
        inclusion: "NA24143"
      NA24631_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG005_NA24631_son/latest/GRCh37/HG005_GRCh37_1_22_v4.2.1_benchmark.bed"
        inclusion: "NA24631"
      NA24694_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG006_NA24694_father/latest/GRCh37/HG006_GRCh37_1_22_v4.2.1_benchmark.bed"
        inclusion: "NA24694"
      NA24695_high_confidence:
        bed: "https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/ChineseTrio/HG007_NA24695_mother/latest/GRCh37/HG007_GRCh37_1_22_v4.2.1_benchmark.bed"
        inclusion: "NA24695"
    stratification-regions:
      ftp: "ftp-trace.ncbi.nlm.nih.gov"
      dir: "ReferenceSamples/giab/release/genome-stratifications/v3.1/GRCh37"
      region-definitions:
        - name: "*"
          label: "All available variants"
          inclusion: ".*"
        - name: "alldifficultregions"
          label: "Union of all tandem repeats, all homopolymers >6bp, all imperfect homopolymers >10bp, all difficult to map regions, all segmental duplications, GC <25% or >65%, \"Bad Promoters\", chrX/Y XTR and ampliconic, satellites and \"OtherDifficult\" regions."
          inclusion: ".*"
        - name: "notinalldifficultregions"
          label: "Variation left after removing all above difficult regions"
          inclusion: ".*"
        - name: "alllowmapandsegdupregions"
          label: "Union of all difficult to map regions and all segmental duplications"
          inclusion: ".*"
        - name: "notinalllowmapandsegdupregions"
          label: "Variation left after removing difficult to map and segmental duplication regions"
          inclusion: ".*"
        - name: "HG001_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA12878"
          inclusion: "NA12878"
        - name: "HG002_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA24385"
          inclusion: "NA24385"
        - name: "HG003_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA24149"
          inclusion: "NA24149"
        - name: "HG004_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA24143"
          inclusion: "NA24143"
        - name: "HG005_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA24631"
          inclusion: "NA24631"
        - name: "HG006_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA24694"
          inclusion: "NA24694"
        - name: "HG007_v4.2.1_CNVsandSVs"
          label: "CNVs and SVs from various sources specific to NA24695"
          inclusion: "NA24695"
