$schema: "https://json-schema.org/draft/2020-12/schema"
description: global configuration
properties:
  experiment-manifest:
    type: string
  reference-manifest:
    type: string
  comparisons-manifest:
    type: string
  genome-build:
    type: string
    pattern: "^grch[0-9]+$"
  genomes:
    type: object
    patternProperties:
      "^grch[0-9]+$":
        type: object
        properties:
          fasta:
            type: string
        required:
          - fasta
        additionalProperties: no
required:
  - experiment-manifest
  - reference-manifest
  - comparisons-manifest
  - genome-build
  - genomes
additionalProperties: no
